version: 2

updates:
  - package-ecosystem: 'nuget'
    schedule:
      interval: 'weekly'
    directory: '/'
    open-pull-requests-limit: 10
    versioning-strategy: 'auto'
    target-branch: 'main'
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major']