trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
  submodules: true

- task: dependabot@1
  inputs:
    setAutoComplete: true
    mergeStrategy: 'squash'
    gitHubAccessToken: '$(GITHUB_ACCESS_TOKEN)'
    azureDevOpsAccessToken: '$(System.AccessToken)'
    dockerImageRepository: 'tinglesoftware/dependabot-updater'
    dockerImageTag: '0.15.0'
    extraEnvironmentVariables: 'EXCON_DEBUG=1'